# Generated by Django 5.0.4 on 2024-04-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_post_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
