# Generated by Django 5.0.4 on 2024-04-12 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
